name          'example42-quantum'
version       '3.0.0-alpha1'
source        'https://github.com/example42/puppet-quantum'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages quantum'
description   'This module installs and manages quantum'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
