name          'example42-quantum'
version       '0.0.1'
source        'UNKNOWN'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages quantum'
description   'UNKNOWN'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
